const path = require('path');
const fs = require('fs');
const os = require('os');
const { app, session } = require('electron');

function getYtDlpPath() {
  const isWin = process.platform === 'win32';
  const isMac = process.platform === 'darwin';
  const binName = isWin ? 'yt-dlp.exe' : 'yt-dlp';
  const repoRoot = path.join(__dirname, '..', '..');

  // macOS: check common install locations (Electron from Finder has limited PATH)
  if (isMac) {
    const macPaths = [
      '/opt/homebrew/bin/yt-dlp',
      '/usr/local/bin/yt-dlp',
      path.join(os.homedir(), '.local/bin/yt-dlp'),
    ];
    try {
      const pyLibDir = path.join(os.homedir(), 'Library', 'Python');
      if (fs.existsSync(pyLibDir)) {
        fs.readdirSync(pyLibDir)
          .filter(d => /^\d+\.\d+$/.test(d))
          .sort((a, b) => parseFloat(b) - parseFloat(a))
          .forEach(v => macPaths.push(path.join(pyLibDir, v, 'bin', 'yt-dlp')));
      }
    } catch (_) {}
    for (const p of macPaths) {
      if (fs.existsSync(p)) return p;
    }
    return binName;
  }

  const subDir = isWin ? 'win' : 'linux';
  const dev = path.join(repoRoot, 'bin', subDir, binName);
  if (fs.existsSync(dev)) return dev;
  if (process.resourcesPath) {
    const bundled = path.join(process.resourcesPath, 'bin', subDir, binName);
    if (fs.existsSync(bundled)) return bundled;
  }
  if (!isWin) {
    for (const p of ['/usr/local/bin/yt-dlp', '/usr/bin/yt-dlp', path.join(os.homedir(), '.local/bin/yt-dlp')]) {
      if (fs.existsSync(p)) return p;
    }
  }
  return binName;
}

function quoteCookieValue(value) {
  return String(value ?? '').replace(/\r?\n/g, '');
}

async function exportElectronYoutubeCookies() {
  try {
    const cookies = await session.defaultSession.cookies.get({});
    const youtubeCookies = cookies.filter(cookie => {
      const domain = String(cookie.domain || '').replace(/^\./, '');
      return domain === 'youtube.com' || domain.endsWith('.youtube.com') ||
        domain === 'google.com' || domain.endsWith('.google.com');
    });
    if (!youtubeCookies.length) return null;

    const filePath = path.join(app.getPath('userData'), 'yt-dlp-youtube-cookies.txt');
    const lines = [
      '# Netscape HTTP Cookie File',
      '# Generated by AudioHoard for yt-dlp. Do not share this file.',
      ...youtubeCookies.map(cookie => {
        const httpOnlyPrefix = cookie.httpOnly ? '#HttpOnly_' : '';
        const domain = cookie.domain || '';
        const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const secure = cookie.secure ? 'TRUE' : 'FALSE';
        const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
        return [
          httpOnlyPrefix + domain,
          includeSubdomains,
          cookie.path || '/',
          secure,
          expires,
          quoteCookieValue(cookie.name),
          quoteCookieValue(cookie.value),
        ].join('\t');
      }),
    ];
    fs.writeFileSync(filePath, lines.join('\n') + '\n', { encoding: 'utf8', mode: 0o600 });
    return filePath;
  } catch (_) {
    return null;
  }
}

async function getYtDlpAuthArgs() {
  const cookiesFile = process.env.SNOWIFY_YTDLP_COOKIES || process.env.YTDLP_COOKIES;
  if (cookiesFile) return ['--cookies', cookiesFile];

  const cookiesFromBrowser = process.env.SNOWIFY_YTDLP_COOKIES_FROM_BROWSER || process.env.YTDLP_COOKIES_FROM_BROWSER;
  if (cookiesFromBrowser) return ['--cookies-from-browser', cookiesFromBrowser];

  const electronCookies = await exportElectronYoutubeCookies();
  return electronCookies ? ['--cookies', electronCookies] : [];
}

module.exports = { getYtDlpPath, getYtDlpAuthArgs };
